### PR TITLE
Add minimal PHP version in composer.json

### PR DESCRIPTION
**Pull request by joanhey**
## Description
Require minimum PHP version.
Now install with any version, but later it will not work.

And inform to any developer only reading the `composer.json`.

Added also php extensions json and zip, as the documentation explain that are needed.
We can remove the need for extensions, but need to be added to the modules that need it.
But in reallity the App load automatically modules than need it.

### CODE REVIEW

**Review by mychidarko — CHANGES_REQUESTED** [review]
@joanhey you can make the minimum requirement v7.4

**Comment by joanhey** [comment]
Already made https://github.com/leafsphp/leaf/pull/210/commits/0b00257ac0cab0a26090595ad36a30e212682a2c
in the last commit.

**Review by mychidarko — APPROVED** [review]

**Comment by mychidarko** [comment]
Oh awesome. Merging now.

**Comment by mychidarko** [comment]
Thanks for the contributions @joanhey. These are a really big help ❤️

**Pull request merged**
